server:
  port: 8082

spring:
  application:
    name: user-exam-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/examdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:parag}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    clean-disabled: false
    clean-on-validation-error: true
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:prabal.soni.cmfeb26@gmail.com}
    password: ${MAIL_PASSWORD:rtqhmhlpmrmefmgh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

question-service:
  url: ${QUESTION_SERVICE_URL:http://localhost:8081}

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh-expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
